In [37]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [38]:
data = pd.read_csv("Social_Network_Ads.csv")

In [39]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [40]:
data = data.drop("User ID", axis=1)

In [41]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [42]:
dependet =data[["Purchased"]]

independet =data[["Age", "EstimatedSalary", "Gender_Male"]]

In [43]:
independet.head()

Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [44]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:


# Define the parameter grid
param_grid = [
    {'penalty': ['l1'], 'C': np.logspace(-4, 4, 20), 'solver': ['liblinear', 'saga'], 'max_iter': [100, 200, 300]},
   ]

# Initialize GridSearchCV with f1_weighted scoring
grid_search = GridSearchCV(LogisticRegression(), param_grid=param_grid, cv=5, verbose=2, n_jobs=-1, scoring='f1_weighted')

# Fit the model
grid_search.fit(X_train, y_train)

# Best hyperparameters
print(f"Best Hyperparameters: {grid_search.best_params_}")


Fitting 5 folds for each of 120 candidates, totalling 600 fits
Best Hyperparameters: {'C': 0.08858667904100823, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'}


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:

# Predict on the test set
y_pred = grid_search.predict(X_test)

In [49]:
re = grid.cv_results_
re
grid_predictions = grid_search.predict(X_test)

In [50]:
grid_predictions

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
cm

array([[73,  6],
       [ 7, 34]], dtype=int64)

In [52]:
from sklearn.metrics import classification_report

In [53]:
clf_report = classification_report(y_test, y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120



In [58]:
from sklearn.metrics import roc_auc_score

y_proba = grid_search.best_estimator_.predict_proba(X_test)[:, 1]


In [59]:
roc_auc_score(y_test, y_proba)

0.9462797159617166

In [61]:
grid_search.predict([[31 ,118000,1]])

array([1], dtype=int64)

In [66]:
#age_input = float(input("Age:"))
#bmi_input = float(input("BMI:"))
#childern_input = float(input("Childern:"))
#sex_male_input = float(input("Sex Male 0 or 1:"))
#smoker_yes_input = float(input("smoker Yes 0 or 1:"))

Age:44
BMI:23
Childern:33
Sex Male 0 or 1:3
smoker Yes 0 or 1:1


In [63]:
#importing pickle file and  used for serializing and deserializing Python objects. 
#import pickle
#model saved in save fomat
#filenmae = 'Logisticclassificationgrid.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
#pickle.dump(grid_search, open(filenmae, 'wb'))

In [65]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
#loaded_model = pickle.load(open('Logisticclassification.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
#result = loaded_model.predict([[33,149000,1]])
#pring the result
#print(result)

[0]


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
