In [1]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")

In [3]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [4]:
data = data.drop("User ID", axis=1)

In [5]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [6]:
dependet =data[["Purchased"]]

independet =data[["Age", "EstimatedSalary", "Gender_Male"]]

In [7]:
independet.head()

Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [8]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.model_selection import GridSearchCV

In [12]:


# Define the parameter grid

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}
    

# Initialize GridSearchCV with f1_weighted scoring
grid = GridSearchCV(RandomForestClassifier(), param_grid=param_grid, cv=5, verbose=2, n_jobs=-1, scoring='f1_macro')

# Fit the model
grid.fit(X_train, y_train)

# Best hyperparameters
print(f"Best Hyperparameters: {grid.best_params_}")


Fitting 5 folds for each of 216 candidates, totalling 1080 fits


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


Best Hyperparameters: {'bootstrap': True, 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}


In [13]:

# Predict on the test set
y_pred = grid.predict(X_test)

In [14]:
re = grid.cv_results_
re
grid_predictions = grid.predict(X_test)

In [15]:
grid_predictions

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
cm

array([[73,  6],
       [ 4, 37]], dtype=int64)

In [17]:
from sklearn.metrics import classification_report

In [18]:
clf_report = classification_report(y_test, y_pred)

In [19]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



In [20]:
from sklearn.metrics import roc_auc_score

y_proba = grid.best_estimator_.predict_proba(X_test)[:, 1]


In [21]:
roc_auc_score(y_test, y_proba)

0.9700524853349799

In [22]:
grid.predict([[31 ,118000,1]])

array([1], dtype=int64)

In [63]:
#importing pickle file and  used for serializing and deserializing Python objects. 
#import pickle
#model saved in save fomat
#filenmae = 'Logisticclassificationgrid.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
#pickle.dump(grid_search, open(filenmae, 'wb'))

In [65]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
#loaded_model = pickle.load(open('Logisticclassification.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
#result = loaded_model.predict([[33,149000,1]])
#pring the result
#print(result)

[0]


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
