In [1]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [19]:
data = pd.read_csv("Social_Network_Ads.csv")

In [20]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [21]:
data = data.drop("User ID", axis=1)

In [22]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [23]:
dependet =data[["Purchased"]]

independet =data[["Age", "EstimatedSalary", "Gender_Male"]]

In [24]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [25]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 10,criterion = 'entropy', random_state=0 )
#regressor is fitting the X-train and y_train data
classifier.fit(X_train,y_train)

C:\Users\AB92922\AppData\Local\Temp\ipykernel_18976\2550333674.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [26]:
y_pred = classifier.predict(X_test)

In [27]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[72,  7],
       [ 6, 35]], dtype=int64)

In [29]:
from sklearn.metrics import classification_report

In [30]:
clf_report = classification_report(y_test, y_pred)

In [32]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.92      0.91      0.92        79
           1       0.83      0.85      0.84        41

    accuracy                           0.89       120
   macro avg       0.88      0.88      0.88       120
weighted avg       0.89      0.89      0.89       120



Precision: Precision measures the accuracy of the positive predictions made by the model.

For class 0 (not purchased), the precision is 0.92. This means that out of all instances predicted as "not purchased" by the model, 92% were actually "not purchased".
For class 1 (purchased), the precision is 0.83. This indicates that out of all instances predicted as "purchased" by the model, 83% were actually "purchased".


Recall: Recall measures the model's ability to find all the positive instances.

For class 0 (not purchased), the recall is 0.91. This means that the model correctly identified 91% of the actual "not purchased" instances.
For class 1 (purchased), the recall is 0.85. This indicates that the model captured 85% of the actual "purchased" instances.


F1-score: The F1-score is the harmonic mean of precision and recall. It provides a single metric that combines both precision and recall.

For class 0 (not purchased), the F1-score is 0.92. This reflects the balance between precision and recall for "not purchased".
For class 1 (purchased), the F1-score is 0.84. This indicates a good balance between precision and recall for "purchased".


Support: Support is the number of actual occurrences of each class in the test set.

For class 0 (not purchased), there are 79 instances.
For class 1 (purchased), there are 41 instances.


Accuracy: The overall accuracy of the model across both classes is 0.89, meaning that the model predicted 89% of instances correctly.

Macro Average:

The macro-averaged precision, recall, and F1-score are all around 0.88. This indicates a balanced performance across classes, considering each class equally.
Weighted Average:

The weighted average precision, recall, and F1-score are all around 0.89. This reflects the overall performance of the model, considering class imbalances, as each class's contribution to the average is weighted by its support.

In [33]:
classifier.predict([[41,44444,1]])

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [34]:
#importing pickle file and  used for serializing and deserializing Python objects. 
import pickle
#model saved in save fomat
filenmae = 'RFclassification.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
pickle.dump(classifier, open(filenmae, 'wb'))

In [36]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
loaded_model = pickle.load(open('RFclassification.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
result = loaded_model.predict([[41,44444,1]])
#pring the result
print(result)

[0]


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
