In [2]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Social_Network_Ads.csv")

In [4]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [5]:
data = data.drop("User ID", axis=1)

In [6]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [7]:
dependet =data[["Purchased"]]

independet =data[["Age", "EstimatedSalary", "Gender_Male"]]

In [8]:
independet.head()

Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [9]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [10]:
from sklearn.svm import SVC

classifier = SVC(kernel = 'rbf', random_state=0 )
#regressor is fitting the X-train and y_train data
classifier.fit(X_train,y_train)

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=0)

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[77,  2],
       [23, 18]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report

In [15]:
clf_report = classification_report(y_test, y_pred)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.77      0.97      0.86        79
           1       0.90      0.44      0.59        41

    accuracy                           0.79       120
   macro avg       0.83      0.71      0.73       120
weighted avg       0.81      0.79      0.77       120



Precision:

For "not purchased" (class 0): Precision is 0.77. This means that out of all instances predicted as "not purchased" by the model, 77% were actually "not purchased".
For "purchased" (class 1): Precision is 0.90. This indicates that out of all instances predicted as "purchased" by the model, 90% were actually "purchased".
Recall (Sensitivity):

For "not purchased" (class 0): Recall is 0.97. This means that the model correctly identified 97% of the actual "not purchased" instances.
For "purchased" (class 1): Recall is 0.44. This indicates that the model captured 44% of the actual "purchased" instances.
F1-score:

For "not purchased" (class 0): The F1-score is 0.86. This reflects the balance between precision and recall for "not purchased".
For "purchased" (class 1): The F1-score is 0.59. This indicates a moderate balance between precision and recall for "purchased".
Support:

For "not purchased" (class 0): There are 79 instances of "not purchased" in the test set.
For "purchased" (class 1): There are 41 instances of "purchased" in the test set.
Accuracy:

The overall accuracy of the model across both classes is 0.79, meaning that the model predicted 79% of instances correctly.
Macro Average:

The macro-averaged precision, recall, and F1-score are 0.83, 0.71, and 0.73 respectively. This indicates a moderate performance across classes.
Weighted Average:

The weighted average precision, recall, and F1-score are 0.81, 0.79, and 0.77 respectively. This reflects the overall performance of the model, considering class imbalances.

In [17]:
classifier.predict([[33,111111,1]])

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [18]:
#importing pickle file and  used for serializing and deserializing Python objects. 
import pickle
#model saved in save fomat
filenmae = 'SVRclassification.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
pickle.dump(classifier, open(filenmae, 'wb'))

In [20]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
loaded_model = pickle.load(open('SVRclassification.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
result = loaded_model.predict([[12,555555,1]])
#pring the result
print(result)

[0]


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
