In [52]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [70]:
#Reading the csv file using pandas function and saved in data variable
data = pd.read_csv("50_Startups.csv")

In [71]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [72]:
data.head()

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   
3  144372.41       118671.85        383199.62  182901.99              0   
4  142107.34        91391.77        366168.42  166187.94              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [73]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [74]:
dependet =data[["Profit"]]

independet =data[["R&D Spend","Administration", "Marketing Spend", "State_Florida","State_New York"]]

In [75]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

In [76]:
#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [77]:
X_train.size, X_test.size, y_train.size, y_test.size

(175, 75, 35, 15)

In [30]:
from sklearn.svm import SVR

In [31]:
regressor = SVR(kernel = "rbf")

In [32]:
#regressor is fitting the X-train and y_train data
regressor.fit(X_train,y_train)

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [37]:
regressor.intercept_

array([108728.18979984])

In [38]:
regressor.n_support_

array([34])

In [39]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [33]:
#machine learning regressor (regressor) to make predictions and saved in y_pred variable
y_pred = regressor.predict(X_test)
y_pred

array([108723.33311607, 108731.86427852, 108730.79788397, 108723.79078234,
       108736.81238961, 108735.84319372, 108724.83721106, 108721.40614577,
       108734.33347855, 108736.81076121, 108728.12634625, 108727.00699914,
       108723.84922275, 108728.09086649, 108734.41129864])

In [34]:
#importing r2_score libarary from sklearn.metrics for model evaulvation
from sklearn.metrics import r2_score

In [35]:
#checking r2 square value between y_test and y_pred
r2_score =r2_score(y_test,y_pred)

In [36]:
#printing r2 square value   # without standardising value
r2_score

-0.05731730927224388

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #transfrom perform caluclation   (mu,sigma)
X_test = sc.fit_transform(X_test)

In [46]:
X_train[20]

array([ 0.42966802,  0.13827054,  0.37625394,  2.        , -0.76870611])

In [48]:
regressor = SVR(kernel = "rbf")
#regressor is fitting the X-train and y_train data
regressor.fit(X_train,y_train)

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [49]:
regressor.n_support_
regressor.intercept_

array([108734.04106363])

In [50]:
#machine learning regressor (regressor) to make predictions and saved in y_pred variable
y_pred = regressor.predict(X_test)
y_pred

array([108733.05053878, 108735.50508937, 108735.76456445, 108729.26677088,
       108737.29199154, 108737.56888511, 108731.55407795, 108732.84704844,
       108735.81627282, 108737.46428305, 108731.14636533, 108732.25424954,
       108732.37686794, 108732.30724376, 108736.81423982])

In [51]:
#checking r2 square value between y_test and y_pred
r2_score =r2_score(y_test,y_pred)
#printing r2 square value   #  standardising value
r2_score

TypeError: 'numpy.float64' object is not callable

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #transfrom perform caluclation   (mu,sigma)
X_test = sc.fit_transform(X_test)

In [79]:
X_train

array([[ 1.17644103,  0.84515251,  0.94354978,  2.        , -0.76870611],
       [ 0.96420324,  1.27283565,  0.42738817,  2.        , -0.76870611],
       [-1.47369826,  0.0153175 , -1.52350329, -0.5       ,  1.30088727],
       [-1.48308929, -2.79556363, -1.53809178, -0.5       ,  1.30088727],
       [-0.14952431,  1.13637282, -0.71716495, -0.5       ,  1.30088727],
       [ 0.85312042, -0.04431628,  0.46771725, -0.5       ,  1.30088727],
       [-0.22353674, -0.3151007 , -0.83981652,  2.        , -0.76870611],
       [-0.19454707,  0.21199679, -1.18497259, -0.5       , -0.76870611],
       [ 0.10478723, -0.08388412,  0.48740807, -0.5       , -0.76870611],
       [-1.0096458 , -1.07019473, -0.4040623 , -0.5       , -0.76870611],
       [ 0.06872897, -0.38396487,  0.75036616, -0.5       , -0.76870611],
       [-1.17638797,  0.14067421, -1.26581817, -0.5       ,  1.30088727],
       [ 0.97648631,  0.9689421 ,  0.84958395, -0.5       ,  1.30088727],
       [ 0.39131191,  0.45560401,  0.3

In [82]:
from sklearn.svm import SVR

In [83]:
regressor = SVR(kernel = "rbf")
#regressor is fitting the X-train and y_train data
regressor.fit(X_train,y_train)

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [84]:
regressor.n_support_


array([34])

In [85]:
regressor.intercept_

array([108734.04106363])

In [86]:
#machine learning regressor (regressor) to make predictions and saved in y_pred variable
y_pred = regressor.predict(X_test)
y_pred

array([108733.05053878, 108735.50508937, 108735.76456445, 108729.26677088,
       108737.29199154, 108737.56888511, 108731.55407795, 108732.84704844,
       108735.81627282, 108737.46428305, 108731.14636533, 108732.25424954,
       108732.37686794, 108732.30724376, 108736.81423982])

In [81]:
from sklearn.svm import SVR

In [87]:
#checking r2 square value between y_test and y_pred
r2_score =r2_score(y_test,y_pred)
#printing r2 square value   #  standardising value
r2_score

TypeError: 'numpy.float64' object is not callable

In [69]:
y_pred

array([108733.05053878, 108735.50508937, 108735.76456445, 108729.26677088,
       108737.29199154, 108737.56888511, 108731.55407795, 108732.84704844,
       108735.81627282, 108737.46428305, 108731.14636533, 108732.25424954,
       108732.37686794, 108732.30724376, 108736.81423982])