In [4]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("Social_Network_Ads.csv")

In [6]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [7]:
data = data.drop("User ID", axis=1)

In [8]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [9]:
dependet =data[["Purchased"]]

independet =data[["Age", "EstimatedSalary", "Gender_Male"]]

In [31]:
independet[1:8]

Age  EstimatedSalary  Gender_Male
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1
5   27            58000            1
6   27            84000            0
7   32           150000            0

In [32]:
dependet =data[["Purchased"]]
dependet[1:8]

Purchased
1          0
2          0
3          0
4          0
5          0
6          0
7          1

In [10]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [11]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion = 'entropy', random_state=0 )
#regressor is fitting the X-train and y_train data
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
X_train.head()

Age  EstimatedSalary  Gender_Male
92    26            15000            1
223   60           102000            1
234   38           112000            0
232   40           107000            1
377   42            53000            0

In [14]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[71,  8],
       [ 3, 38]], dtype=int64)

In [16]:
from sklearn.metrics import classification_report

In [17]:
clf_report = classification_report(y_test, y_pred)

In [18]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        79
           1       0.83      0.93      0.87        41

    accuracy                           0.91       120
   macro avg       0.89      0.91      0.90       120
weighted avg       0.91      0.91      0.91       120



•  Precision:
•	For "not purchased" (class 0): Precision is 0.96, indicating that out of all instances predicted as "not purchased" by the model, 96% were actually "not purchased".
•	For "purchased" (class 1): Precision is 0.83, meaning that out of all instances predicted as "purchased" by the model, 83% were actually "purchased".


•  Recall (Sensitivity):
•	For "not purchased" (class 0): Recall is 0.90, indicating that the model correctly identified 90% of the actual "not purchased" instances.
•	For "purchased" (class 1): Recall is 0.93, indicating that the model captured 93% of the actual "purchased" instances.


•  F1-score:
•	For "not purchased" (class 0): The F1-score is 0.93, reflecting the balance between precision and recall for "not purchased".
•	For "purchased" (class 1): The F1-score is 0.87, indicating a good balance between precision and recall for "purchased".
•  Support:
•	For "not purchased" (class 0): There are 79 instances of "not purchased" in the test set.
•	For "purchased" (class 1): There are 41 instances of "purchased" in the test set.


•  Accuracy: The overall accuracy is 0.91, meaning that the model predicted 91% of instances correctly across both classes.


•  Macro Average:
•	The macro-averaged precision, recall, and F1-score are all around 0.89-0.91, indicating a balanced performance across classes.

•  Weighted Average:
•	The weighted average precision, recall, and F1-score are all around 0.91, reflecting the overall performance of the model considering class imbalances.



In [35]:
classifier.predict([[45,22000,1]])

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [36]:
#importing pickle file and  used for serializing and deserializing Python objects. 
import pickle
#model saved in save fomat
filenmae = 'DTclassification.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
pickle.dump(classifier, open(filenmae, 'wb'))

In [38]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
loaded_model = pickle.load(open('DTclassification.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
result = loaded_model.predict([[27,137000,1]])
#pring the result
print(result)

[1]


C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
