In [71]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [72]:
#Reading the csv file using pandas function and saved in data variable
data = pd.read_csv("50_Startups.csv")

In [73]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [74]:
data.head()

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   
3  144372.41       118671.85        383199.62  182901.99              0   
4  142107.34        91391.77        366168.42  166187.94              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [75]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [76]:
dependet =data[["Profit"]]

independet =data[["R&D Spend","Administration", "Marketing Spend", "State_Florida","State_New York"]]

In [77]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [78]:
X_train.size, X_test.size, y_train.size, y_test.size

(175, 75, 35, 15)

In [79]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #transfrom perform caluclation   (mu,sigma)
X_test = sc.fit_trans(X_test)

In [80]:
X_train


array([[ 1.17644103,  0.84515251,  0.94354978,  2.        , -0.76870611],
       [ 0.96420324,  1.27283565,  0.42738817,  2.        , -0.76870611],
       [-1.47369826,  0.0153175 , -1.52350329, -0.5       ,  1.30088727],
       [-1.48308929, -2.79556363, -1.53809178, -0.5       ,  1.30088727],
       [-0.14952431,  1.13637282, -0.71716495, -0.5       ,  1.30088727],
       [ 0.85312042, -0.04431628,  0.46771725, -0.5       ,  1.30088727],
       [-0.22353674, -0.3151007 , -0.83981652,  2.        , -0.76870611],
       [-0.19454707,  0.21199679, -1.18497259, -0.5       , -0.76870611],
       [ 0.10478723, -0.08388412,  0.48740807, -0.5       , -0.76870611],
       [-1.0096458 , -1.07019473, -0.4040623 , -0.5       , -0.76870611],
       [ 0.06872897, -0.38396487,  0.75036616, -0.5       , -0.76870611],
       [-1.17638797,  0.14067421, -1.26581817, -0.5       ,  1.30088727],
       [ 0.97648631,  0.9689421 ,  0.84958395, -0.5       ,  1.30088727],
       [ 0.39131191,  0.45560401,  0.3

In [81]:
y_train

Profit
7   155752.60
14  132602.65
45   64926.08
48   35673.41
29  101004.64
15  129917.04
30   99937.59
32   97427.84
16  126992.93
42   71498.49
20  118474.03
43   69758.98
8   152211.77
13  134307.35
25  107404.34
5   156991.12
17  125370.37
40   78239.91
49   14681.40
1   191792.06
12  141585.52
37   89949.14
24  108552.04
6   156122.51
23  108733.99
36   90708.19
21  111313.02
19  122776.86
9   149759.96
39   81005.76
46   49490.75
3   182901.99
0   192261.83
47   42559.73
44   65200.33

In [82]:
scy = StandardScaler()
y_train = scy.fit_transform(y_train) #transfrom perform caluclation   (mu,sigma)
y_test = scy.fit_transform(y_test)

In [83]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators = 500,max_features='sqrt',max_depth=None, min_samples_split=2, min_samples_leaf=1, bootstrap=True,criterion='mse')
#regressor is fitting the X-train and y_train data
regressor.fit(X_train,y_train)

C:\Users\AB92922\AppData\Local\Temp\ipykernel_3756\1256958438.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)
C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', max_features='sqrt', n_estimators=500)

In [84]:
#machine learning regressor (regressor) to make predictions and saved in y_pred variable
y_pred = regressor.predict(X_test)
y_pred

array([-0.37044642,  0.30295218,  0.30184334, -0.98056532,  1.34139423,
        0.43555251, -1.17183371, -0.46564808,  0.0412929 ,  1.27302987,
       -0.53347656, -0.68418261,  0.03315038, -0.45218355,  0.42475706])

In [85]:
#importing r2_score libarary from sklearn.metrics for model evaulvation
from sklearn.metrics import r2_score

In [86]:
#checking r2 square value between y_test and y_pred
r2_score =r2_score(y_test,y_pred)
#printing r2 square value   #  standardising value
r2_score

0.7979406592797388

In [64]:
import pickle
#model saved in save fomat
filename = 'finalizedmodelRFRmodelPreProcessBoth.sav'

In [87]:
pre_inputs = sc.transform([[13000,12000,4000,1,1]])
pre_inputs

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.72177156, -3.32899006, -2.53802461,  0.81649658,  1.6583124 ]])

In [88]:
import pickle
#model saved in save fomat
filename = 'finalizedmodelRFRmodelPreProcessBoth.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [68]:
#import pickle
#model saved in save fomat
#filename = 'finalizedmodelRFRmodelPreProcess.sav'
#pickle.dump() serializes the regressor object and writes it to the specified file (filename) in binary mode ('wb').
#pickle.dump(regressor, open(filename, 'wb'))

In [89]:
# the mode 'rb' used in file operations stands for "read binary" and saved in laoded model
loaded_model = pickle.load(open('finalizedmodelRFRmodelPreProcessBoth.sav','rb'))
#using predict keyeword, predicting 15 years of experience of emplyee and predicted value store in result variable
result = loaded_model.predict(pre_inputs)
#pring the result
print(result)

[-1.52311588]


In [92]:
pre_output = scy.inverse_transform([result])
pre_output

array([[68862.23183129]])